###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: slack-bot-mysql
      working_dir: /application
      restart: always
      volumes:
        - ./phpdocker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/z_my.cnf
        - ./phpdocker/mysql/dump:/docker-entrypoint-initdb.d
        - .:/application
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=secret
        - TZ=UTC
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: slack-bot-webserver
      working_dir: /application
      restart: always
      volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
            - "8080:80"
            
    php-fpm:
      build: phpdocker/php-fpm
      container_name: slack-bot-php-fpm
      working_dir: /application
      restart: always
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        
