###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mysql:5.7
      container_name: slackbot-mysql
      working_dir: /application
      volumes:
        - ./phpdocker/mysql/dump:/docker-entrypoint-initdb.d
        - .:/application
      restart: always
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=slackbot
        - MYSQL_USER=slackbot
        - MYSQL_PASSWORD=123456
        - MYSQL_ROOT_HOST=127.0.0.1
      ports:
        - "3003:3306"
      command: --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=ROW --server-id=1
        
    webserver:
      image: nginx:alpine
      container_name: slackbot-webserver
      working_dir: /application
      restart: always
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: slackbot-php-fpm
      working_dir: /application
      restart: always
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

